services:
    twitter.client:
        class: TwitterBundle\Services\Twitter
        arguments: ["@doctrine.orm.default_entity_manager", "@service_container"]

parameters:
    consumer_key:     ""
    consumer_secret:  ""
    token:            ""
    token_secret:     ""